//LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL
#ifndef SEDHOM_LINKEDLIST_DATA_STRUCTURE_H
#define SEDHOM_LINKEDLIST_DATA_STRUCTURE_H
//LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL
template<typename T>
class Node
{
    public:
        T value ;
        Node<T> * next ;
        Node(T val)
        {
            this->value = val;
            this->next = nullptr;
        }
};
//LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL
template<typename T>
class LinkedList
{
    private:
        Node<T>* head ;   
    public:
      LinkedList();
     ~LinkedList();  
     void add_end(T val);

};
//LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL
#endif //SEDHOM_LINKEDLIST_DATA_STRUCTURE_H
//LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL