//NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
#include "SEDHOM_Font_definations.h"
//NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
Font SEDHOM_Font_definations::Default()
{
    return Font(FONT_Default_BIG);
}
Font SEDHOM_Font_definations::Serif()
{
    return Font(FONT_FREESERIF_MEDIUM);
}
Font SEDHOM_Font_definations::Mono()
{
    return Font(FONT_FREEMONO_MEDIUM);
}
//NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
