//PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP
#ifndef SEDHOM_PRIMITIVE_TYPES_H_
#define SEDHOM_PRIMITIVE_TYPES_H_
//PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP

//PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP
// 8-bit
typedef signed char             S_int8_t;
typedef unsigned char           U_int8_t;

// 16-bit
typedef signed short            S_int16_t;
typedef unsigned short          U_int16_t;

// 32-bit
typedef signed long             S_int32_t;
typedef unsigned long           U_int32_t;

// 64-bit
typedef signed long long        S_int64_t;
typedef unsigned long long      U_int64_t;

// Floating
typedef float                   F_float;
typedef double                  F_double;
typedef long double             F_long_double;
//PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP
typedef S_int8_t                byte_t;
//PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP
#endif // !SEDHOM_PRIMITIVE_TYPES_H_
//PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP