//YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY
#ifndef STACK_DATA_STRUTURE_H_
#define STACK_DATA_STRUTURE_H_
//YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY
//YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY
template<typename T>
class Stack
{
    private:
        T* array;
        int size;
        int top;

    public:
        Stack() : array(nullptr), size(0), top(-1) {}
        Stack(int Stack_size);
        ~Stack();

        void init_Stack(int Stack_size);
        bool isEmpty();
        bool isFull();
        void push(T value);
        T pop();
        T peek();
};
//YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY
#endif // !STACK_DATA_STRUTURE_H_
//YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY