//XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
#ifndef SEDHOM_TEXT_STYLE_H_
#define SEDHOM_TEXT_STYLE_H_
//XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
#include "../../../../SEDHOM_GUI_Core/SEDHOM_Colors/SEDHOM_Colors.h"
#include "../../../../SEDHOM_Utilits/SEDHOM_Data_Types/SEDHOM_Data_Types.h"
#include "../SEDHOM_Font_Style/SEDHOM_Font_definations.h"
#include "../SEDHOM_Font_Style/SEDHOM_Font_Style.h"
//XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
//XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
class SEDHOM_Text_Style : private SEDHOM_Font_definations
{
private:
    Color_t _color;
    Font _font;

public:
    SEDHOM_Text_Style& font(Font font = Font()) ;
    SEDHOM_Text_Style& color(Color_t color = Color_Blue) ;
    // gets
    Font getFont()  const ;
    Color_t getColor() const ;
};
//XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
#endif // !SEDHOM_TEXT_STYLE_H_
//XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX